language: ruby
rvm:
  - 2.5.0

env:
  DB_USER: postgres
  DB_PASSWORD: ''
  DB_HOST: localhost

before_install:
  - gem update --system
  - gem update bundler

cache: bundler

script:
  - bundle exec rake db:create db:migrate
  - bundle exec rake spec
  - bundle exec rubocop
  - bundle exec brakeman
  - bundle exec reek
  - bundle exec rails_best_practices -e "db/migrate,vendor" .

services:
  - postgresql
